test: avoid test failures because pool has been defined
Avoid errors with the following pattern:

ERROR    Error: --disk /var/tmp/*.qcow2,format=qcow2,target=vda: Could
not define storage pool: operation failed: pool 'tmp' already exists
with uuid *

subprocess.CalledProcessError: Command '['virt-xml', '-c', 'qemu:///session',
'fedora-rawhide-boot-127.0.0.2-2201', '--update', '--add-device', '--disk',
'/var/tmp/*.qcow2,format=qcow2,target=vda']' returned non-zero exit status 1.