webui: pin down cockpit-* packages versions for gating purposes
Some recent regression on cockpit has broken CI.

All tests now fail with:

Traceback (most recent call last):
File "/usr/bin/cockpit-bridge", line 5, in <module>
from cockpit.bridge import main
ModuleNotFoundError: No module named 'cockpit'

Possible Selinux AVC denial causing it:
AVC avc:  denied  { execute_no_trans } for  pid=6772 comm="cockpit-ws"
path="/usr/bin/cockpit-bridge" dev="overlay" ino=715 scontext=system_u:system_r:kernel_t:s0
tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=1

This needs to be reverted once the issue is resolved.